# Generated by Django 3.2.12 on 2025-10-23 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL别名')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '应用分类',
                'verbose_name_plural': '应用分类',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='网站名称')),
                ('url', models.URLField(max_length=500, verbose_name='网站链接')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/', verbose_name='网站图标')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '网站导航',
                'verbose_name_plural': '网站导航',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='应用名称')),
                ('version', models.CharField(max_length=50, verbose_name='应用版本')),
                ('short_description', models.TextField(blank=True, verbose_name='简短描述')),
                ('logo', models.ImageField(upload_to='app_logos/', verbose_name='应用Logo')),
                ('install_method', models.CharField(choices=[('EXTERNAL', '外链'), ('UPLOAD', '本机上传'), ('SERVER_FILE', '服务器文件'), ('SILENT', '静默安装'), ('MANUAL', '手动安装')], default='MANUAL', max_length=15, verbose_name='安装方式')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('download_type', models.CharField(choices=[('EXTERNAL', '外链'), ('UPLOAD', '本机上传'), ('SERVER_FILE', '服务器文件'), ('SILENT', '静默安装'), ('MANUAL', '手动安装')], default='UPLOAD', max_length=15, verbose_name='下载类型')),
                ('external_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='外链地址')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='app_files/', verbose_name='本机上传文件')),
                ('server_file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='服务器文件路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.category', verbose_name='应用分类')),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
