# Generated by Django 3.2.12 on 2025-10-23 16:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['order', 'name'], 'verbose_name': '应用', 'verbose_name_plural': '应用'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'created_at'], 'verbose_name': '应用分类', 'verbose_name_plural': '应用分类'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='install_method',
        ),
        migrations.RemoveField(
            model_name='application',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='websitenavigation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.category', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='application',
            name='download_type',
            field=models.CharField(choices=[('EXTERNAL_LINK', '外部链接'), ('UPLOADED_FILE', '本机上传'), ('SERVER_PATH', '手动选择服务器文件')], default='UPLOADED_FILE', max_length=20, verbose_name='下载方式'),
        ),
        migrations.AlterField(
            model_name='application',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='外部链接'),
        ),
        migrations.AlterField(
            model_name='application',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=200, verbose_name='应用名称'),
        ),
        migrations.AlterField(
            model_name='application',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='简短描述'),
        ),
        migrations.AlterField(
            model_name='application',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='本机上传文件'),
        ),
        migrations.AlterField(
            model_name='application',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='websitenavigation',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons/', verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='websitenavigation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='网站名称'),
        ),
        migrations.AlterField(
            model_name='websitenavigation',
            name='url',
            field=models.URLField(max_length=500, verbose_name='网址'),
        ),
    ]
