# Generated by Django 3.2.12 on 2025-10-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251024_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='install_method',
            field=models.CharField(choices=[('SILENT', '静默安装'), ('MANUAL', '手动安装')], default='MANUAL', max_length=10, verbose_name='安装方式'),
        ),
        migrations.AddField(
            model_name='application',
            name='install_params',
            field=models.CharField(blank=True, help_text='仅当安装方式为“静默安装”时生效，用于存储安装包的静默参数 (如：/S, /qn /norestart)。', max_length=255, null=True, verbose_name='安装参数'),
        ),
    ]
