# Generated by Django 4.2.25 on 2025-10-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20251024_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['order', 'name'], 'verbose_name': '应用管理', 'verbose_name_plural': '应用管理'},
        ),
    ]
